"""
gen_migration_012.py
Generates supabase/migrations/012_reseed_price_database.sql
- Step 1: DELETE commercial/niche subcategories
- Step 2: UPSERT 208 verified seed items × 4 regions
"""

import os
import sys

# Add scripts dir to path so we can import ITEMS from build_price_db
sys.path.insert(0, os.path.dirname(__file__))
from build_price_db import ITEMS

OUTPUT = os.path.join(os.path.dirname(__file__), '..', 'supabase', 'migrations', '012_reseed_price_database.sql')

def esc(s):
    return str(s).replace("'", "''")

def avg(a, b):
    return round((a + b) / 2, 2)

lines = []

lines.append("-- Migration 012: Clean commercial items + reseed price database with verified market data")
lines.append("-- Generated by scripts/gen_migration_012.py")
lines.append("-- 208 items × 4 regions (MY_KL, MY_PG, MY_JB, SG)")
lines.append("")

# -----------------------------------------------------------------------
# STEP 1: DELETE commercial/niche categories entirely
# -----------------------------------------------------------------------
lines.append("-- ============================================================")
lines.append("-- STEP 1: DELETE commercial/niche categories entirely")
lines.append("-- ============================================================")
lines.append("")

niche_categories = ['Commercial Specialty', 'Fire Safety', 'Signage']
for cat in niche_categories:
    lines.append(f"DELETE FROM price_database WHERE category = '{cat}';")

lines.append("")

# -----------------------------------------------------------------------
# STEP 2: DELETE commercial subcategories within valid categories
# -----------------------------------------------------------------------
lines.append("-- ============================================================")
lines.append("-- STEP 2: DELETE commercial subcategories in valid categories")
lines.append("-- ============================================================")
lines.append("")

# Air Conditioning
lines.append("DELETE FROM price_database WHERE category = 'Air Conditioning' AND subcategory IN ('Commercial HVAC', 'VRV/VRF System');")

# Aluminium & Glass
lines.append("DELETE FROM price_database WHERE category = 'Aluminium & Glass' AND subcategory = 'Commercial';")
lines.append("DELETE FROM price_database WHERE category IN ('Aluminium', 'Glass') AND subcategory = 'Commercial';")

# Carpentry
lines.append("DELETE FROM price_database WHERE category = 'Carpentry' AND subcategory IN ('Commercial', 'F&B Fitout', 'Office Fitout');")

# Electrical
lines.append("DELETE FROM price_database WHERE category = 'Electrical' AND subcategory IN "
             "('Commercial Electrical', 'Mall Electrical', 'Office Electrical', 'Retail Electrical', "
             "'F&B Electrical', 'Industrial', 'BMS/Building Management');")

# Flooring
lines.append("DELETE FROM price_database WHERE category = 'Flooring' AND subcategory IN ('Commercial', 'Commercial Flooring');")

# Metal Work
lines.append("DELETE FROM price_database WHERE category = 'Metal Work' AND subcategory IN ('Commercial', 'Industrial');")

# Painting
lines.append("DELETE FROM price_database WHERE category = 'Painting' AND subcategory IN ('Commercial', 'F&B Painting', 'Industrial Coating');")

# Plumbing
lines.append("DELETE FROM price_database WHERE category = 'Plumbing' AND subcategory IN ('Commercial', 'F&B Plumbing', 'Industrial');")

# Demolition
lines.append("DELETE FROM price_database WHERE category = 'Demolition' AND subcategory IN ('Reinstatement', 'Commercial Demolition');")

# Construction (Condo Work is a legit subcat but without independent data → keep; Commercial Construction → remove)
lines.append("DELETE FROM price_database WHERE category = 'Construction' AND subcategory IN ('Commercial Construction', 'Mall Construction', 'Industrial Construction');")

# Security System
lines.append("DELETE FROM price_database WHERE category = 'Security System' AND subcategory IN ('Access Control', 'Mall Security', 'Commercial Security');")

# Condo Work in any category (these are formula-derived duplicates, not independent data)
lines.append("DELETE FROM price_database WHERE subcategory = 'Condo Work';")

# Landscape
lines.append("DELETE FROM price_database WHERE category = 'Landscape' AND subcategory IN ('Commercial Landscape', 'Golf Course');")

lines.append("")

# -----------------------------------------------------------------------
# STEP 3: UPSERT 208 seed items × 4 regions
# -----------------------------------------------------------------------
lines.append("-- ============================================================")
lines.append("-- STEP 3: UPSERT 208 verified seed items (4 regions each)")
lines.append("-- Conflict key: (category, subcategory, material_method, unit, supply_type, region)")
lines.append("-- ============================================================")
lines.append("")

upsert_rows = []

for item in ITEMS:
    cat   = esc(item['cat'])
    sub   = esc(item['subcat'])
    meth  = esc(item['method'])
    name  = esc(item['name'])
    unit  = esc(item['unit'])
    sup   = esc(item['supply'])

    kl_min = item['kl_min']
    kl_max = item['kl_max']
    kl_avg = avg(kl_min, kl_max)

    # JB = KL; PG = JB = KL
    jb_min, jb_max, jb_avg = kl_min, kl_max, kl_avg
    pg_min, pg_max, pg_avg = kl_min, kl_max, kl_avg

    sg_min = item.get('sg_min')
    sg_max = item.get('sg_max')

    # MY_KL
    upsert_rows.append(
        f"('{cat}','{sub}','{meth}','{name}','{unit}','{sup}','MY_KL',{kl_min},{kl_max},{kl_avg},1,'high')"
    )
    # MY_PG
    upsert_rows.append(
        f"('{cat}','{sub}','{meth}','{name}','{unit}','{sup}','MY_PG',{pg_min},{pg_max},{pg_avg},1,'low')"
    )
    # MY_JB
    upsert_rows.append(
        f"('{cat}','{sub}','{meth}','{name}','{unit}','{sup}','MY_JB',{jb_min},{jb_max},{jb_avg},1,'low')"
    )
    # SG — only insert if we have real prices
    if sg_min is not None and sg_max is not None:
        sg_avg = avg(sg_min, sg_max)
        upsert_rows.append(
            f"('{cat}','{sub}','{meth}','{name}','{unit}','{sup}','SG',{sg_min},{sg_max},{sg_avg},1,'high')"
        )

# Chunk into batches of 100 to stay readable
CHUNK = 100
col_list = "(category, subcategory, material_method, item_name, unit, supply_type, region, min_price, max_price, avg_price, sample_count, confidence)"
conflict_key = "(category, subcategory, material_method, unit, supply_type, region)"
update_clause = ("min_price = EXCLUDED.min_price, max_price = EXCLUDED.max_price, "
                 "avg_price = EXCLUDED.avg_price, item_name = EXCLUDED.item_name, "
                 "confidence = EXCLUDED.confidence, sample_count = EXCLUDED.sample_count")

for i in range(0, len(upsert_rows), CHUNK):
    chunk = upsert_rows[i:i+CHUNK]
    batch_num = i // CHUNK + 1
    lines.append(f"-- Batch {batch_num} ({i+1}–{min(i+CHUNK, len(upsert_rows))} of {len(upsert_rows)} rows)")
    lines.append(f"INSERT INTO price_database {col_list}")
    lines.append("VALUES")
    lines.append(",\n".join(f"  {r}" for r in chunk))
    lines.append(f"ON CONFLICT {conflict_key}")
    lines.append(f"DO UPDATE SET {update_clause};")
    lines.append("")

lines.append(f"-- Total UPSERT rows: {len(upsert_rows)}")
lines.append(f"-- Total seed items: {len(ITEMS)}")
lines.append("-- Migration complete.")

sql = "\n".join(lines)
out_path = os.path.normpath(OUTPUT)
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(sql)

print(f"Written: {out_path}")
print(f"Items: {len(ITEMS)}, Rows: {len(upsert_rows)}")
